name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Hello world action
      #   with: # Set the secret as an input
      #     GITHUB_TOKEN: ${{ secrets.MONGO_SERV }}
      #   env: # Or as an environment variable
      #     GITHUB_TOKEN: ${{ secrets.MONGO_SERV }}
      #   run: |
      # example-command "$SUPER_SECRET}}
      - name: Inject secrets into config
        run: |
          echo "window._env_ = {GITHUB_TOKEN: '${{ secrets.MONGO_SERV }}'};" > env.js
      - name: Deploy to GitHub Pages
        uses: afham123/QNA@v3
        with:
          github_token: ${{ secrets.MONGO_SERV }}
          publish_dir: ./
