name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
    steps:
  - name: Hello world action
    with: # Set the secret as an input
      GITHUB_TOKEN: ${{ secrets.MONGO_SERV }}
    env: # Or as an environment variable
      GITHUB_TOKEN: ${{ secrets.MONGO_SERV }}

  - name: Inject secrets into config
    run: |
      echo "window._env_ = {GITHUB_TOKEN: '${{ secrets.MONGO_SERV }}'};" > env.js
